export {
  DISTANCE_STEP_KM,
  DURATION_STEP_SECONDS,
  REPS_STEP,
  WEIGHT_STEP,
  decrementValue,
  formatRir,
  incrementValue,
  rirChoices,
  roundDistance,
  setTypeLabel,
  setTypeMarker,
  setTypeOptions,
  toNullableInteger,
  toNullableMinutes,
  toNullableNumber,
} from './model/setInput'
